ENV['RACK_ENV'] ||= 'development'
require 'sinatra/base'
require_relative 'data_mapper_setup'
require 'sinatra/flash'
require_relative 'controllers/users'
require_relative 'controllers/spaces'
require_relative 'controllers/sessions'
require_relative 'controllers/requests'
require_relative 'server'
